name: CoHackJourney

on: [ push ]

env:                                   #Workflow-level
  WORKSHOP_NAME: "GH-200 CoHack"
  TRAINER: "Himanshu"

jobs:
  setup:
    env:
      JOB_ENV: "Setup Phase"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Say Hello
        run: echo "Hello from the GH_200 Session"

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: List files
        run: ls -la
      - name: Tiemout step
        timeout-minutes: 1
        run: |
          sleep 30
          echo "successful run"

  test:
    runs-on: ${{ matrix.os}}
    needs: setup
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11"]
        exclude:
          - os: windows-latest
            python-version: 3.10
      fail-fast: false
      max-parallel: 3
    steps:
     - name: Print value
       run: echo "Test job run successfull     
