name: CoHackJourney

on: [ push ]

env:                                   #Workflow-level
  WORKSHOP_NAME: "GH-200 CoHack"
  TRAINER: "Himanshu"

jobs:
  setup:
    env:
      JOB_ENV: "Setup Phase"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Say Hello
        run: echo "Hello from the GH_200 Session"

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: List files
        run: ls -la
      - name: Tiemout step
        timeout-minutes: 1
        run: sleep 70
 
