name: CoHackJourney

on: [ push ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from the GH_200 Session"

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: List files
        run: ls -la
